@baseUrl=http://127.0.0.1:3000
@apiUrl={{baseUrl}}/api/v1

###
GET {{baseUrl}} HTTP/1.1

###
# @name subscriptionCreate
POST {{apiUrl}}/subscriptions HTTP/1.1
Content-Type: application/json

{
    "uuid": "{{$guid}}",
    "url": "https://example.com/{{$randomInt 0 100}}",
    "secret": "{{$randomString 32}}",
    "events": ["invoice.created"]
}

###
@subscriptionUUID={{subscriptionCreate.response.body.$.uuid}}
GET {{apiUrl}}/subscriptions?uuid={{subscriptionUUID}} HTTP/1.1

###
GET {{apiUrl}}/subscriptions/{{subscriptionUUID}} HTTP/1.1

###
DELETE {{apiUrl}}/subscriptions/{{subscriptionUUID}} HTTP/1.1

###
POST {{apiUrl}}/events HTTP/1.1
Content-Type: application/json

{
    "id": "evt_001",
    "type": "invoice.created",
    "payload": {
        "id": "inv_001",
        "amount": 99.0
    }
}