@baseUrl=http://127.0.0.1:3000

###
GET {{baseUrl}} HTTP/1.1

###
# @name subscriptionCreate
POST {{baseUrl}}/subscriptions HTTP/1.1
Content-Type: application/json

{
    "uuid": "{{$guid}}",
    "url": "https://example.com/{{$randomInt 0 100}}",
    "secret": "{{$randomString 32}}",
    "events": ["invoice.created"]
}

###
@subscriptionID={{subscriptionCreate.response.body.$.uuid}}
GET {{baseUrl}}/subscriptions?uuid={{subscriptionID}} HTTP/1.1

###
GET {{baseUrl}}/subscriptions/{{subscriptionID}} HTTP/1.1

###
DELETE {{baseUrl}}/subscriptions/{{subscriptionID}} HTTP/1.1
